FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

COPY requirements.embedder.txt ./requirements.embedder.txt
RUN pip install -r requirements.embedder.txt

COPY src ./src

CMD ["python", "-m", "embedding_service.main"]
