[mypy]
python_version = 3.10
mypy_path = src
explicit_package_bases = True
strict = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_untyped_calls = True
implicit_optional = False
warn_unused_ignores = True
warn_unused_configs = True
warn_redundant_casts = True
show_error_codes = True
plugins = pydantic.mypy
exclude = (?x)(^\.venv/|^dist/|^build/|^migrations/|^tests/.*/__init__\.py$)

[mypy-psycopg2]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-openpyxl]
ignore_missing_imports = True

[pydantic-mypy]
init_typed = True
warn_required_dynamic_aliases = True
